
Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop" do |v|
    v.gui = false  # Set to true if you need a GUI
  end
  
  config.vm.define "prometheus-grafana" do |monitor|
    monitor.vm.box = "koalephant/debian12"

    #monitor.vm.architecture = "arm64"
    monitor.vm.network "private_network", ip: "192.168.33.13"
      redis.vm.network "forwarded_port", guest: 3000, host: 3000

#     monitor.vm.provision "shell", inline: <<-SHELL
#       apt-get update
#       apt-get install -y prometheus grafana mysql-client apache2-utils
#       wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.11.0/mysqld_exporter-0.11.0.linux-amd64.tar.gz
#       tar xvfz mysqld_exporter-0.11.0.linux-amd64.tar.gz
#       mv mysqld_exporter-0.11.0.linux-amd64/mysqld_exporter /usr/local/bin/
#       echo "starting prometheus and grafana"
#       systemctl start prometheus
#       systemctl enable prometheus
#       systemctl start grafana-server
#       systemctl enable grafana-server
#     SHELL
#   end
 end
