
Vagrant.configure("2") do |config|
  config.ssh.keep_alive = true

  config.vm.provider "vmware_desktop" do |v|
    v.gui = false  # Set to true if you need a GUI
  end
  	
  config.vm.define "laravel-app" do |laravel|
    laravel.vm.box = "koalephant/debian12"
   # laravel.vm.architecture = "arm64"
    laravel.vm.network "private_network", ip: "192.168.33.10"
    laravel.vm.network "forwarded_port", guest: 80, host: 8085
    laravel.vm.provision "shell", inline: <<-SHELL
      echo 'cd /var/www/html' >> /home/vagrant/.bashrc
      apt-get update
      apt-get install -y apache2 php php-cli git php-mbstring php-xml php-bcmath php-mysql unzip curl mariadb-server  
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer

      git clone https://github.com/chriscupas/todo_with_auth.git /var/www/html/todo
      cp /var/www/html/todo/.env.example /var/www/html/todo/.env 

      # Set up environment variables for MySQL in Laravel's .env file
      sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' /var/www/html/todo/.env
      sed -i 's/^DB_HOST=.*/DB_HOST=192.168.33.11/' /var/www/html/todo/.env
      sed -i 's/^DB_PORT=.*/DB_PORT=3306/' /var/www/html/todo/.env
      sed -i 's/^DB_DATABASE=.*/DB_DATABASE=laravel_db/' /var/www/html/todo/.env
      sed -i 's/^DB_USERNAME=.*/DB_USERNAME=laravel_user/' /var/www/html/todo/.env
      sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=laravel_password/' /var/www/html/todo/.env
          # Update .env file for Redis configuration
      sed -i 's/^REDIS_HOST=.*/REDIS_HOST=192.168.33.15/' /var/www/html/todo/.env && \
      sed -i 's/^REDIS_PORT=.*/REDIS_PORT=6379/' /var/www/html/todo/.env && \
      sed -i 's/^REDIS_PASSWORD=.*/REDIS_PASSWORD=null/' /var/www/html/todo/.env && \
      sed -i 's/^REDIS_CLIENT=.*/REDIS_CLIENT=phpredis/' /var/www/html/todo/.env
      
      sudo chmod -R 0777 /var/www/html/todo/storage
      sudo chmod -R 0777 /var/www/html/todo/bootstrap
      # Run Laravel migrations
      cd /var/www/html/todo
      composer install --ignore-platform-reqs
      php artisan key:generate
      php artisan migrate --force

      # Set the Apache document root to /var/www/html/todo/public
sudo bash -c 'cat > /etc/apache2/sites-available/000-default.conf <<EOL
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/todo/public

    <Directory /var/www/html/todo/public>
        AllowOverride All
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOL'

      a2enmod rewrite
      service apache2 restart

 
 chown -R www-data:www-data /var/www/html
 chmod -R g+w /var/www/html
 usermod -aG www-data vagrant

   
    SHELL
  end

 end
