
Vagrant.configure("2") do |config|
  config.ssh.keep_alive = true

  config.vm.provider "vmware_desktop" do |v|

    v.gui = false  # Set to true if you need a GUI
  end
  	
  config.vm.define "redis" do |redis|
    redis.vm.box = "koalephant/debian12"
   # redis.vm.architecture = "arm64"
    redis.vm.network "private_network", ip: "192.168.33.15"
    redis.vm.network "forwarded_port", guest: 6379, host: 63799
    redis.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y redis-server
      sudo sed -i 's/^bind .*/bind 0.0.0.0/' /etc/redis/redis.conf && \
      sudo sed -i 's/^protected-mode .*/protected-mode no/' /etc/redis/redis.conf
      
      sudo systemctl restart redis-server
    SHELL
  end

 end
